### ISSUE TITLE
Investigate troubles caused by Spock integration

### ISSUE THREAD

**Issue by phejl** [moditect/jfrunit#72]
Reported here https://github.com/junit-team/junit5/commit/eaab286a53d534966de7cf6200955c0d3b8830f4. I need to check in more depth but perhaps one nice idea would be to have the support not dependant on the `JfrEventTest` annotation (global spock extension). If I understand that correctly Quarkus support works like that. It would make usage even simpler.

cc @gunnarmorling @sbrannen

**Comment by sbrannen** [comment]
FYI: The reason the JUnit 5 build failed is due to a "feature" of the Java compiler.

Many people (including me) consider this an outright bug in the Java compiler (because types are allowed to be annotated with annotation types that are not present in the current classpath at runtime), but the Java team at Oracle apparently do not see it that way (at least not when we discussed it with them at Devoxx back in 2017 (I believe that was the year)).

In any case, if you would like some more background information on the issue, see the following.

- https://github.com/junit-team/junit5/issues/1105
- https://github.com/google/guava/issues/2721

**Comment by sbrannen** [comment]
Please keep in mind that having `@JfrEventTest` meta-annotated with `@ExtendWith(JfrEventTestExtension.class)` will result in the same error encountered in the JUnit build for projects that use JfrJunit with Spock but without JUnit Jupiter on their classpath.

**Comment by gunnarmorling** [comment]
> types are allowed to be annotated with annotation types that are not present in the current classpath at runtime

Just cannot not comment on this one :) I think the current behavior is desirable, as it allows to re-use annotated classes in different contexts. The canonical example being JPA entities which can be used as data structures on the client-side, without the need for having the persistence API on the classpath there.

**Comment by sbrannen** [comment]
@gunnarmorling, I think you misunderstood the point I was trying to make (likely because I was too vague).

> I think the current behavior is desirable, as it allows to re-use annotated classes in different contexts. The canonical example being JPA entities which can be used as data structures on the client-side, without the need for having the persistence API on the classpath there.

Yes, that's a great feature of Java. No doubt. We love it!

But... the Java compiler emits a warning if you try to use a third-party annotation in your own code when that third-party annotation is meta-annotated with a second third-party annotation that is not present in the class path.

And... if you compile with `-Werror` (which many projects do), your build fails.

We argued with the Java team that such a condition should not result in a warning that can fail the build, _because_ of the fact that the exact same code (once compiled) works fine at runtime without the second third-party annotation on the classpath.

Does that make sense now?

**Comment by gunnarmorling** [comment]
Ah yes, got it now. Indeed I understood exactly the opposite of what you meant to say :) So yes, I agree there should be a way for _compiling_ the code of this situation without any warnings (and without supressing other, unrelated, warnings), if that code can _be run_ just fine later on.
